### Register
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "testR",
  "email": "testRade@example.com",
  "password": "testR"
}

### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "testRade@example.com",
  "password": "testR"
}

### Get all surveys for user
GET http://localhost:8000/api/survey
Content-Type: application/json

### Get single survey
GET http://localhost:8000/api/survey/60080eb500f89ec2003d442e
Content-Type: application/json

### Create survey
POST http://localhost:8000/api/survey
Content-Type: application/json

{
  "name": "Survey 1",
  "userId": "1",
  "description": "lorem ipsum"
}

### Update survey
PUT http://localhost:8000/api/survey/60080eb500f89ec2003d442e
Content-Type: application/json

{
  "name": "Survey 3",
  "userId": "1",
  "description": "lorem ipsum 3"
}

### Delete survey
DELETE http://localhost:8000/api/survey/60080b9f00a688030046ca8b
Content-Type: application/json